### ISSUE TITLE
parallelization

### ISSUE THREAD

**Issue by tcorodrigues** [alexarnimueller/cats-descriptor#3]
Hey Alex!
My understanding of the code is that input/output order is not necessarily the same when it parallelises. Correct?

**Comment by alexarnimueller** [comment]
Hey Tiago
I was actually not sure, so I now added a new feature that allows you to supply compound IDs in the input file.
If you don't supply IDs, it will create a range for the number of molecules and return these with the result.
Hope that helps.
Cheers,
Alex

**Comment by tcorodrigues** [comment]
My PhD student noticed it when calculating CATS for FDA approved mols.
I was implementing a solution along the lines of:

else:
        chunks = np.array_split(np.array(mols), cpu_count())
        procs = []
        for i, chunk in enumerate(chunks):
            p = Process(target=_cats_corr, args=(chunk, queue,))
            p.start()
            procs.append(p)
        
        temp = [None] * len(mols)
        for i in range(len(procs)):
            temp[i::len(procs)] = queue.get()

        for i, res in enumerate(temp):
            rslt[i] = res
        
        for p in procs:
            p.join()
        
    return np.array(rslt).astype('float32')

... but it remains untested and you were faster :)
Thanks a lot! 
Tiago
